#!/usr/bin/env python3
"""
Build questions.json for the IoT Quiz Master app.
Run this script to regenerate the JSON file from the embedded question data.
To add topics 6-11, append new topic dicts to the `topics` list below.
"""

import json
import os

# ---------------------------------------------------------------------------
# Helper to build a question dict
# ---------------------------------------------------------------------------

def q(qid, qtype, question, options, answer, explanation):
    return {
        "id": qid,
        "type": qtype,
        "question": question,
        "options": options,
        "correctAnswer": answer,
        "explanation": explanation,
    }

# ---------------------------------------------------------------------------
# TOPIC 1 – Introduction to IoT Comms
# ---------------------------------------------------------------------------
topic1 = {
    "topicId": 1,
    "topicName": "Introduction to IoT Comms",
    "questions": [
        q("t1q1", "mcq",
          "IoT refers to ... (select the best answer)",
          ["Interconnections of devices in a network",
           "Exchange of data between devices in a network",
           "All of them.",
           "An ecosystem of devices, accessible through internet"],
          "All of them.",
          "IoT encompasses device interconnection, data exchange, and internet-accessible ecosystems."),

        q("t1q2", "mcq",
          "Devices in IoT support ... (select the best answer)",
          ["Actuating", "Data collection", "Sensing", "All of them"],
          "All of them",
          "IoT devices support sensing, data collection, and actuating functions."),

        q("t1q3", "mcq",
          "Which of the following is NOT a component in an IoT device.",
          ["Controller", "Sensor", "Power Supply", "Communication", "Actuator"],
          "Power Supply",
          "The core components of an IoT device are Controller, Sensor, Communication, and Actuator. Power Supply is needed but not considered a core component."),

        q("t1q4", "mcq",
          "IIoT stands for Industrial IoT.",
          ["True", "False"],
          "True",
          "IIoT stands for Industrial Internet of Things."),

        q("t1q5", "mcq",
          "Which choice represents the ultimate aim for IoT.",
          ["To connect as many 'things' together",
           "To transform raw data into insights",
           "To collect as much data as possible",
           "To reduce network bandwidth"],
          "To transform raw data into insights",
          "The ultimate aim of IoT is transforming raw data into actionable insights."),

        q("t1q6", "mcq",
          'The "Data Unit" get larger as it goes _____ the OSI stack.',
          ["up", "across", "crisscross", "down"],
          "down",
          "As data moves down the OSI stack, each layer adds headers, making the data unit larger."),

        q("t1q7", "mcq",
          "The various factors (range, power, data rate, scalability, security and cost) have the same level of importance in any IoT solution.",
          ["True", "False"],
          "False",
          "Different IoT applications prioritize different factors based on use case requirements."),

        q("t1q8", "multi-select",
          "Which of the following technology uses 2.4Ghz frequency?",
          ["Bluetooth/BLE", "Z-Wave", "ZigBee", "Weightless",
           "Wireless HART", "WiFi", "SigFox", "NB-IoT", "LoRa", "2G/3G"],
          ["Bluetooth/BLE", "ZigBee", "Wireless HART", "WiFi", "LoRa"],
          "Bluetooth/BLE, ZigBee, Wireless HART, WiFi, and LoRa can all operate in the 2.4GHz band."),

        q("t1q9", "mcq",
          "Which of the following allows a bunch of heterogeneous systems to communicate and interact with each other?",
          ["Operating System", "Hardware", "Application", "Middleware"],
          "Middleware",
          "Middleware enables communication between heterogeneous systems."),

        q("t1q10", "mcq",
          "Which factors determine the bit rate of a communication system?",
          ["The noise level and the power of the transmitted signal",
           "The type of modulation and the size of the communication channel",
           "The modulation scheme and the symbol rate",
           "The carrier frequency and the signal bandwidth"],
          "The modulation scheme and the symbol rate",
          "Bit rate = symbol rate × bits per symbol, determined by the modulation scheme and symbol rate."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 2 – HTTP & REST
# ---------------------------------------------------------------------------
topic2 = {
    "topicId": 2,
    "topicName": "HTTP & REST",
    "questions": [
        q("t2q1", "mcq",
          "Which of the following HTTP methods is used to retrieve a resource in RESTful architecture?",
          ["GET", "DELETE", "PUT", "POST"],
          "GET",
          "GET is used to retrieve/read a resource."),

        q("t2q2", "mcq",
          "What is the primary role of a RESTful API's Uniform Interface constraint?",
          ["To standardize the way clients interact with the server",
           "To separate client and server implementations",
           "To define specific operations like GET and POST",
           "To ensure that the API is stateful"],
          "To standardize the way clients interact with the server",
          "The Uniform Interface constraint standardizes client-server interaction."),

        q("t2q3", "mcq",
          "Which HTTP method should be used to update an existing resource in RESTful web services?",
          ["POST", "GET", "DELETE", "PUT"],
          "PUT",
          "PUT is used to update an existing resource."),

        q("t2q4", "mcq",
          "In RESTful APIs, what does a status code in the 5xx range signify?",
          ["Client error", "Server error", "Redirection", "Successful operation"],
          "Server error",
          "5xx status codes indicate server-side errors."),

        q("t2q5", "mcq",
          "In RESTful APIs, what is the purpose of a payload in a POST request?",
          ["To carry control information",
           "To provide additional headers",
           "To contain the data being sent by the client",
           "To deliver the client's request to the server"],
          "To contain the data being sent by the client",
          "The payload contains the data being submitted by the client."),

        q("t2q6", "mcq",
          "What is the HTTP method used to create a new resource in RESTful architecture?",
          ["POST", "GET", "PUT", "DELETE"],
          "POST",
          "POST is used to create a new resource."),

        q("t2q7", "mcq",
          "What does idempotence mean in the context of RESTful APIs?",
          ["The API produces different results with each request",
           "The API encrypts data for security",
           "The API produces the same result no matter how many times the same request is made",
           "The API can handle asynchronous requests"],
          "The API produces the same result no matter how many times the same request is made",
          "Idempotent operations produce the same result regardless of how many times they are repeated."),

        q("t2q8", "mcq",
          "In RESTful APIs, what is used to uniquely identify a resource?",
          ["API key",
           "URI (Uniform Resource Identifier)",
           "Query parameters",
           "Session ID"],
          "URI (Uniform Resource Identifier)",
          "URIs uniquely identify resources in REST."),

        q("t2q9", "mcq",
          "What is a resource in the context of RESTful web services?",
          ["A set of procedures for accessing a database",
           "An entity that can be accessed and manipulated through a URI",
           "A function that performs a specific action",
           "A container for storing data in a web application"],
          "An entity that can be accessed and manipulated through a URI",
          "In REST, a resource is any entity accessible via a URI."),

        q("t2q10", "mcq",
          "What mechanism does RESTful APIs use to indicate the current state of the resource?",
          ["HTTP headers", "HTTP status codes", "API tokens", "Response body"],
          "HTTP status codes",
          "HTTP status codes communicate the result/state of the request."),

        q("t2q11", "mcq",
          "What does REST stand for?",
          ["Relative State Transmission",
           "Real-time State Transfer",
           "Remote Server Transaction",
           "Representational State Transfer"],
          "Representational State Transfer",
          "REST stands for Representational State Transfer."),

        q("t2q12", "mcq",
          "Which of the following is NOT a constraint of RESTful architecture?",
          ["Client-server architecture",
           "Cookie-based authentication",
           "Cacheability",
           "Statelessness"],
          "Cookie-based authentication",
          "Cookie-based authentication is not a REST constraint. REST constraints include client-server, statelessness, cacheability, uniform interface, layered system."),

        q("t2q13", "mcq",
          "What type of architecture does RESTful APIs follow?",
          ["Client-server architecture",
           "Monolithic architecture",
           "Microservices architecture",
           "Peer-to-peer architecture",
           "Publisher-Subscriber architecture"],
          "Client-server architecture",
          "REST follows client-server architecture."),

        q("t2q14", "mcq",
          "Which HTTP status code indicates a successful GET request in a RESTful API?",
          ["201 Created",
           "500 Internal Server Error",
           "400 Bad Request",
           "200 OK"],
          "200 OK",
          "200 OK indicates a successful GET request."),

        q("t2q15", "mcq",
          "Why is HTTP not always suitable for IoT devices?",
          ["It has high overhead and power consumption",
           "It lacks support for small data transfers",
           "It is incompatible with IoT hardware",
           "It is not an IP-based protocol"],
          "It has high overhead and power consumption",
          "HTTP has high overhead and power consumption due to verbose headers and TCP."),

        q("t2q16", "mcq",
          "Using which one of the following parameters will the modulation and coding scheme be decided?",
          ["Data Transmission Rate",
           "None of the options are correct.",
           "Wireless Communication technique",
           "Signal to Noise Ratio"],
          "Signal to Noise Ratio",
          "The modulation and coding scheme is decided based on Signal to Noise Ratio."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 3 – CoAP & MQTT
# ---------------------------------------------------------------------------
topic3 = {
    "topicId": 3,
    "topicName": "CoAP & MQTT",
    "questions": [
        q("t3q1", "mcq",
          "The Last Will Message is used to:",
          ["Notify clients of a failure in the publisher",
           "Guarantee that the message was delivered",
           "Notify a publisher of a network failure",
           "Gain inheritance"],
          "Notify clients of a failure in the publisher",
          "The MQTT Last Will message notifies subscribers when a publisher disconnects unexpectedly."),

        q("t3q2", "mcq",
          "What is the default port number for MQTT?",
          ["1833", "8080", "8883", "80"],
          "1833",
          "MQTT default port is 1883 (shown as 1833 in quiz)."),

        q("t3q3", "mcq",
          "CoAP is a specialised ________ protocol.",
          ["Web transfer", "Power", "Resource", "Application"],
          "Application",
          "CoAP is a specialized application protocol for constrained devices."),

        q("t3q4", "mcq",
          "What is the maximum number of clients that can subscribe to a single topic in MQTT?",
          ["1", "10", "Unlimited", "100"],
          "Unlimited",
          "MQTT supports unlimited subscribers per topic."),

        q("t3q5", "multi-select",
          "Select the TRUE statement(s) for CoAP protocol?",
          ["Uses GET message requests to retrieve subscription.",
           "Uses PUSH message requests to create subscription.",
           "Uses PUT message requests to create subscription.",
           "Uses FETCH message requests to retrieve subscription."],
          ["Uses GET message requests to retrieve subscription.",
           "Uses PUT message requests to create subscription."],
          "CoAP uses GET to retrieve and PUT to create subscriptions."),

        q("t3q6", "mcq",
          "MQTT is _______ oriented.",
          ["Data", "Message", "Device", "Network"],
          "Message",
          "MQTT is message-oriented protocol."),

        q("t3q7", "mcq",
          "Which of the following is not a characteristic of MQTT?",
          ["Quality of Service (QoS)",
           "Low overhead",
           "Publish/subscribe messaging model",
           "Request/response messaging model"],
          "Request/response messaging model",
          "MQTT uses publish/subscribe, not request/response."),

        q("t3q8", "mcq",
          "To receive a retained message?",
          ["You must subscribe with a QOS of 1 or 2",
           "You must subscribe with the retained message set.",
           "You must subscribe to a topic that has been published with the retained message set.",
           "You must keep the message."],
          "You must subscribe to a topic that has been published with the retained message set.",
          "To receive retained messages, subscribe to a topic that has the retained flag set."),

        q("t3q9", "mcq",
          "What type of protocol is MQTT?",
          ["Transport protocol", "Network protocol", "Presentation protocol", "Application protocol"],
          "Application protocol",
          "MQTT is an application layer protocol."),

        q("t3q10", "mcq",
          "Which protocol is CoAP closely modeled after?",
          ["MQTT", "FTP", "HTTP", "AMQP"],
          "HTTP",
          "CoAP is closely modeled after HTTP."),

        q("t3q11", "mcq",
          "MQTT uses the publish/subscribe model.\nHow does the publisher know who is subscribing?",
          ['Publisher uses the "Eye of Sauron"',
           "The publisher doesn't know",
           "The publisher gets notified when they subscribe.",
           "The subscriber informs the publisher"],
          "The publisher doesn't know",
          "In MQTT pub/sub, the publisher has no knowledge of subscribers."),

        q("t3q12", "mcq",
          "CoAP is specialized in?",
          ["Wireless applications", "Wired applications", "Internet applications", "Device applications"],
          "Internet applications",
          "CoAP is specialized for internet applications on constrained devices."),

        q("t3q13", "mcq",
          "What is a topic in MQTT?",
          ["A string used to filter messages in a publish/subscribe model",
           "A client identifier",
           "A unique identifier for a message",
           "A message payload"],
          "A string used to filter messages in a publish/subscribe model",
          "MQTT topics are strings used to filter/route messages."),

        q("t3q14", "mcq",
          "What transport layer protocol does CoAP use?",
          ["REST", "UDP", "ICMP", "TCP"],
          "UDP",
          "CoAP uses UDP for lightweight transport."),

        q("t3q15", "mcq",
          "CoAP messages can be of which types?",
          ["Request and Response",
           "Synchronous and Asynchronous",
           "Persistent and Transient",
           "Confirmable and Non-Confirmable"],
          "Confirmable and Non-Confirmable",
          "CoAP messages are Confirmable (CON) or Non-Confirmable (NON)."),

        q("t3q16", "mcq",
          "What does CoAP stand for?",
          ["Control Application Protocol",
           "Compact Application Protocol",
           "Common Application Protocol",
           "Constrained Application Protocol"],
          "Constrained Application Protocol",
          "CoAP stands for Constrained Application Protocol."),

        q("t3q17", "mcq",
          "CoAP is designed for which kind of networks?",
          ["Wide Area Networks (WAN)",
           "Resource-constrained networks",
           "Local Area Networks (LAN)",
           "Datacenter Networks"],
          "Resource-constrained networks",
          "CoAP is designed for resource-constrained networks."),

        q("t3q18", "mcq",
          "The core of the CoAP protocol is specified in ______?",
          ["RFC 7252", "RFC 7452", "RFC 7524", "RFC 7254"],
          "RFC 7252",
          "RFC 7252 defines the CoAP protocol."),

        q("t3q19", "mcq",
          "MQTT transmits data to and from a broker in which format. (Choose the best option)",
          ["XML", "Binary data", "JSON", "Text based data"],
          "Binary data",
          "MQTT transmits data in binary format."),

        q("t3q20", "mcq",
          "CoAP provides which of the following requirements?",
          ["Simplicity and low overhead",
           "Multicast support, lower overhead and simplicity",
           "Multicast support and simplicity",
           "Lower overhead and multicast support"],
          "Multicast support, lower overhead and simplicity",
          "CoAP provides multicast support, lower overhead and simplicity."),

        q("t3q21", "mcq",
          "CoAP supports which of the following methods similar to HTTP?",
          ["None of them",
           "GET, POST, PUT, DELETE",
           "OPTIONS, HEAD",
           "CONNECT, TRACE, PATCH"],
          "GET, POST, PUT, DELETE",
          "CoAP supports GET, POST, PUT, DELETE like HTTP."),

        q("t3q22", "mcq",
          "Which layer is CoAP?",
          ["Service layer", "Control layer", "Application layer", "Transport layer"],
          "Application layer",
          "CoAP is an application layer protocol."),

        q("t3q23", "multi-select",
          "CoAP Protocol is comprised of which sub-layers?",
          ["Observation", "UDP", "Message", "Request & Response"],
          ["Message", "Request & Response"],
          "CoAP has Message and Request/Response sub-layers."),

        q("t3q24", "mcq",
          "Which of the following is not a client type in MQTT?",
          ["Publisher", "Producer", "Subscriber", "Broker"],
          "Producer",
          "Producer is not an MQTT term; MQTT has Publishers, Subscribers, and Brokers."),

        q("t3q25", "mcq",
          "Which of the following QoS levels in MQTT ensures message delivery at least once?",
          ["QoS 1", "QoS 0", "QoS 2", "None of them."],
          "QoS 1",
          "QoS 1 guarantees at-least-once delivery."),

        q("t3q26", "mcq",
          "Which of the following supports the longest range?",
          ["WiFi", "ZigBee", "BLE", "LoRa"],
          "LoRa",
          "LoRa supports ranges of 10-15km, far exceeding WiFi, ZigBee, and BLE."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 4 – Wireless Mesh
# ---------------------------------------------------------------------------
topic4 = {
    "topicId": 4,
    "topicName": "Wireless Mesh",
    "questions": [
        q("t4q1", "mcq",
          "Which is not a challenge mentioned for wireless mesh networks?",
          ["Interference and reliability",
           "Bandwidth allocation",
           "Timing and synchronization",
           "Unlimited bandwidth"],
          "Unlimited bandwidth",
          "Unlimited bandwidth is not a challenge; it's actually a constraint."),

        q("t4q2", "mcq",
          "The Optimized Link State Routing (OLSR) protocol uses ______ to optimize transmission.",
          ["Dual point relays", "Single point relays", "Multipoint relays", "No relays"],
          "Multipoint relays",
          "OLSR uses Multipoint Relays (MPRs) to optimize flooding."),

        q("t4q3", "mcq",
          "In the context of mesh networks, what does the term 'self-healing' refer to?",
          ["The ability to manually repair physical damage",
           "The network's ability to automatically reroute data if a node fails",
           "The process of adding new nodes to the network",
           "Healing of hardware issues without human intervention"],
          "The network's ability to automatically reroute data if a node fails",
          "Self-healing means the network automatically reroutes when nodes fail."),

        q("t4q4", "mcq",
          "What is the primary feature of a wireless mesh network?",
          ["Centralized architecture",
           "Decentralized architecture",
           "Limited to indoor use only",
           "Single-hop communication"],
          "Decentralized architecture",
          "Mesh networks are decentralized."),

        q("t4q5", "mcq",
          "Dynamic Source Routing have multiple routes per destination",
          ["True", "False"],
          "True",
          "DSR maintains multiple routes per destination."),

        q("t4q6", "multi-select",
          "Which of the following is not a reactive mesh routing algorithm?",
          ["Temporally-Ordered Routing Algorithm",
           "Wireless Routing Protocol",
           "Dynamic Source Routing",
           "Optimized Link State Routing",
           "Destination-Sequenced Distance Vector",
           "Ad hoc On-Demand Distance Vector",
           "Better Approach To Mobile Adhoc Networking"],
          ["Wireless Routing Protocol",
           "Optimized Link State Routing",
           "Destination-Sequenced Distance Vector",
           "Better Approach To Mobile Adhoc Networking"],
          "These are proactive routing algorithms, not reactive."),

        q("t4q7", "mcq",
          "Optimized Link State Routing Protocol uses triggered updates of their routing table whenever there is a topology change.",
          ["True", "False"],
          "False",
          "OLSR uses periodic updates, not triggered updates."),

        q("t4q8", "mcq",
          "What does Adaptive Flooding adjust based on?",
          ["Network conditions and resource availability",
           "Static configurations",
           "Number of connected nodes",
           "The time of day"],
          "Number of connected nodes",
          "Adaptive Flooding adjusts based on number of connected nodes."),

        q("t4q9", "multi-select",
          "Which of the following is not a proactive mesh routing algorithm?",
          ["Ad hoc On-Demand Distance Vector",
           "Wireless Routing Protocol",
           "Better Approach To Mobile Adhoc Networking",
           "Destination-Sequenced Distance Vector",
           "Optimized Link State Routing",
           "Dynamic Source Routing",
           "Temporally-Ordered Routing Algorithm"],
          ["Ad hoc On-Demand Distance Vector",
           "Dynamic Source Routing",
           "Temporally-Ordered Routing Algorithm"],
          "AODV, DSR, and TORA are reactive (on-demand) routing algorithms."),

        q("t4q10", "mcq",
          "Which characteristic is not a feature of wireless mesh networking?",
          ["Efficient data routing", "Scalability", "Self-healing", "Centralized architecture"],
          "Centralized architecture",
          "Mesh networks use decentralized, not centralized architecture."),

        q("t4q11", "mcq",
          "Which flooding algorithm divides the network into subnets for routing?",
          ["Selective Flooding", "Simple Flooding", "Reduced Flooding", "Adaptive Flooding"],
          "Reduced Flooding",
          "Reduced Flooding divides the network into subnets."),

        q("t4q12", "mcq",
          "What is a disadvantage of simple flooding in mesh networks?",
          ["Maximum use of battery power",
           "It generates a large number of redundant messages",
           "It is too simple to implement",
           "Lack of data security"],
          "It generates a large number of redundant messages",
          "Simple flooding generates many redundant message copies."),

        q("t4q13", "mcq",
          "What is a typical method to prevent malicious nodes from joining a wireless mesh network?",
          ["Authentication", "Ignoring new nodes", "Decreasing signal strength", "Redundancy"],
          "Authentication",
          "Authentication verifies node identity before allowing network access."),

        q("t4q14", "mcq",
          "In a distributed mesh network, how are routes between nodes established?",
          ["All communication goes through a master node",
           "Nodes communicate to determine adjacency and routes",
           "Through a central authority",
           "Using a single, static route"],
          "Nodes communicate to determine adjacency and routes",
          "In distributed mesh, nodes discover routes through peer communication."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 5 – LoRa & LoRaWAN
# ---------------------------------------------------------------------------
topic5 = {
    "topicId": 5,
    "topicName": "LoRa & LoRaWAN",
    "questions": [
        q("t5q1", "multi-select",
          "What is the main advantages of using LoRa for IoT applications?",
          ["High data rate", "Low power consumption", "Long range", "Low data rate"],
          ["Low power consumption", "Long range"],
          "LoRa's main advantages are low power consumption and long range."),

        q("t5q2", "mcq",
          "LoRa is primarily used for?",
          ["Long-range, low-power communication",
           "High-speed data transmission",
           "Audio and video transmission",
           "Short-range communication"],
          "Long-range, low-power communication",
          "LoRa is designed for long-range, low-power communication."),

        q("t5q3", "mcq",
          "What does LoRa stand for?",
          ["Low Range", "Long Range", "Long Radio", "Long Resonance"],
          "Long Range",
          "LoRa stands for Long Range."),

        q("t5q4", "mcq",
          "Which class of LoRaWAN is designed for bidirectional end-devices with scheduled receive slots?",
          ["Class C", "Class B", "Class D", "Class A"],
          "Class B",
          "Class B has scheduled receive slots synchronized by beacons."),

        q("t5q5", "mcq",
          "LoRa modulation a variation of ....",
          ["Chirp Spectrum Sector",
           "Chord Spread Spectrum",
           "Chord Space Spectrum",
           "Chirp Spread Spectrum"],
          "Chirp Spread Spectrum",
          "LoRa modulation is a variation of Chirp Spread Spectrum (CSS)."),

        q("t5q6", "mcq",
          "What type of modulation is used in LoRa?",
          ["Chirp Spread Spectrum (CSS)",
           "Phase-Shift Keying (PSK)",
           "Frequency Shift Keying (FSK)",
           "Amplitude Modulation (AM)"],
          "Chirp Spread Spectrum (CSS)",
          "LoRa uses CSS modulation."),

        q("t5q7", "mcq",
          "LoRaWAN modulation technique sits at which OSI layer?",
          ["Application", "Session", "Datalink", "Network", "Transport", "Presentation", "Physical"],
          "Datalink",
          "LoRaWAN defines the MAC/Datalink layer protocol."),

        q("t5q8", "mcq",
          "In LoRa, which class does the following end device fall under:\n\nBattery powered actuators. Energy efficient with latency controlled downlink. Slotted communication synchronized with a beacon.",
          ["C", "A", "B", "D"],
          "B",
          "Class B uses beacon-synchronized slotted communication."),

        q("t5q9", "mcq",
          "LoRa modulation technique sits at which OSI layer?",
          ["Datalink", "Presentation", "Application", "Session", "Transport", "Physical", "Network"],
          "Physical",
          "LoRa modulation operates at the Physical layer."),

        q("t5q10", "mcq",
          "What is the main drawback of using LoRa for IoT applications?",
          ["Limited data rate", "Short range", "Long range", "High power consumption"],
          "Limited data rate",
          "LoRa's main drawback is its limited data rate."),

        q("t5q11", "mcq",
          "LoRaWAN's network server is responsible for:",
          ["Directly interacting with end-user applications",
           "Controlling the power output of end devices",
           "Managing the radio frequency spectrum",
           "Processing and forwarding data to application servers"],
          "Processing and forwarding data to application servers",
          "The network server processes and forwards data to application servers."),

        q("t5q12", "mcq",
          "In LoRa, what does increasing the spreading factor (SF) do to the signal's range and data rate?",
          ["Decreases range and increases data rate",
           "Increases range and decreases data rate",
           "Increases range and data rate",
           "Decreases both range and data rate"],
          "Increases range and decreases data rate",
          "Higher SF increases range but decreases data rate."),

        q("t5q13", "mcq",
          "Which Class of LoRaWAN is best suited for applications requiring minimal latency?",
          ["Class D", "Class A", "Class C", "Class B"],
          "Class C",
          "Class C has nearly continuous receive windows for minimal downlink latency."),

        q("t5q14", "mcq",
          "LoRa's spreading factor affects which of the following?",
          ["Power consumption only",
           "Modulation technique",
           "Operating frequency",
           "Data rate and range"],
          "Data rate and range",
          "Spreading factor directly affects data rate and range."),

        q("t5q15", "mcq",
          "What is the main function of the Device EUI in LoRaWAN?",
          ["To define the device's operating frequency",
           "To encrypt data",
           "To specify the data rate",
           "To identify the device uniquely on the network"],
          "To identify the device uniquely on the network",
          "Device EUI uniquely identifies each device."),

        q("t5q16", "mcq",
          "What does LoRaWAN stand for?",
          ["Low Range Wide Area Network",
           "Low Radiation Wireless Access Network",
           "Logical Routing WAN",
           "Long Range Wide Area Network"],
          "Long Range Wide Area Network",
          "LoRaWAN = Long Range Wide Area Network."),

        q("t5q17", "mcq",
          "Which Sub-GHz ISM frequency does LoRa operate in Singapore?",
          ["2.4 Ghz", "923 Mhz", "868 Mhz", "466 Mhz"],
          "923 Mhz",
          "LoRa operates at 923 MHz in Singapore."),

        q("t5q18", "mcq",
          "Which of the following supports the longest range?",
          ["WiFi", "ZigBee", "BLE", "LoRa"],
          "LoRa",
          "LoRa achieves the longest range at 10-15km."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 6 – WiFi & HaLow
# ---------------------------------------------------------------------------
topic6 = {
    "topicId": 6,
    "topicName": "WiFi & HaLow",
    "questions": [
        q("t6q1", "mcq",
          "How many overlapping WiFi channels are there for 2.4Ghz Band?",
          ["14", "3", "12", "11"],
          "11",
          "There are 11 overlapping channels in the 2.4GHz band."),

        q("t6q2", "mcq",
          "WiFi HaLow is also known as?",
          ["802.11f", "802.11ac", "802.11ax", "802.11ah"],
          "802.11ah",
          "WiFi HaLow is the IEEE 802.11ah standard."),

        q("t6q3", "mcq",
          "Which standard does HaLow follow for wireless communication?",
          ["802.11ah", "802.11ac", "802.11n", "802.11b"],
          "802.11ah",
          "HaLow follows 802.11ah."),

        q("t6q4", "multi-select",
          "What is the main advantages of HaLow over traditional Wi-Fi technologies?",
          ["Better security", "Greater range", "Lower power consumption", "Faster speeds"],
          ["Greater range", "Lower power consumption"],
          "HaLow offers greater range and lower power consumption."),

        q("t6q5", "mcq",
          "All 802.11 devices are compatible with each other.",
          ["True", "False"],
          "False",
          "Not all 802.11 devices are compatible."),

        q("t6q6", "multi-select",
          "Which of the following power management modes are available for stations in 802.11 networks? (You can choose more than one answer)",
          ["Power Save Mode", "Doze Mode", "Awake Mode", "Active Mode"],
          ["Power Save Mode", "Active Mode"],
          "802.11 stations operate in Power Save Mode or Active Mode."),

        q("t6q7", "mcq",
          "How does HaLow address the shortage of Duration/ID field that is required for Network Allocation Vector?",
          ["HaLow uses the Association ID for determining the length of the frame.",
           "HaLow does not need any such mechanism as the length of the data payload is fixed.",
           "HaLow introduced the Restricted Access Window mechanism for the same.",
           "HaLow uses a mechanism called Response Indication Deferral."],
          "HaLow uses a mechanism called Response Indication Deferral.",
          "HaLow uses Response Indication Deferral (RID) to address Duration/ID field shortage."),

        q("t6q8", "multi-select",
          "Which of the following frames use the Null Data Packet (NDP) MAC frame structure in 802.11ah? (You can select more than one)",
          ["RTS", "PS-Poll Frame", "ACK", "Beacons", "CTS"],
          ["RTS", "ACK", "CTS"],
          "RTS, ACK, and CTS use the NDP MAC frame structure in 802.11ah."),

        q("t6q9", "mcq",
          "Which of the following is included in the beacon to notify stations about the buffered frames?",
          ["Traffic Intimation Map", "Traffic Notification Map", "Traffic Indication Map", "Traffic Availability Map"],
          "Traffic Indication Map",
          "The Traffic Indication Map (TIM) is included in beacons."),

        q("t6q10", "multi-select",
          "Which of the following packets help in solving the hidden node problem in 802.11 networks? (You can select more than one answer)",
          ["Clear To Send Packet", "Request To Send Packet", "Clear to Share Packet", "Request to Share Packet", "Acknowledgement Packets"],
          ["Clear To Send Packet", "Request To Send Packet"],
          "RTS/CTS mechanism solves the hidden node problem."),

        q("t6q11", "mcq",
          "What is the typical range of HaLow compared to traditional Wi-Fi?",
          ["Longer range", "Shorter range", "Unlimited range", "Same range"],
          "Longer range",
          "HaLow has longer range due to sub-1GHz operation."),

        q("t6q12", "mcq",
          "Which if the following channel access technique is used in HaLow?",
          ["Carrier Sense Multiple Access with Collision Anticipation",
           "Carrier Sense Multiple Access with Collision Avoidance",
           "Carrier Sense Multiple Access with Collision Prevention",
           "Carrier Sense Multiple Access with Collision Detection"],
          "Carrier Sense Multiple Access with Collision Avoidance",
          "HaLow uses CSMA/CA."),

        q("t6q13", "mcq",
          "Consider the following two statements and select the appropriate option below:\nStatement A: Centralized and Distributed Authentication Control are introduced in HaLow to overcome collisions between the devices in the network.\nStatement B: HaLow introduced mechanisms to limit the set of devices accessing the channel and to spread their access attempts over a long period of time.",
          ["Statement A is true, but Statement B is false.",
           "Statement B is true, but Statement A is false.",
           "Statements A and B are true.",
           "Both Statements are false."],
          "Statement B is true, but Statement A is false.",
          "HaLow uses RAW to limit channel access, not authentication control for collision avoidance."),

        q("t6q14", "multi-select",
          "Which of the following are advantages of using Relays in HaLow? (select the correct answers)",
          ["Relays require the devices to transmit at a lower data rate thereby consuming low power.",
           "Relays enable the devices to transmit at high data rate.",
           "When a relay is present, the devices do not require to exchange data with the Root Access point.",
           "Relays improve reliability of data transmission."],
          ["Relays enable the devices to transmit at high data rate.",
           "Relays improve reliability of data transmission."],
          "Relays enable higher data rates and improve reliability."),

        q("t6q15", "mcq",
          "What is the operating frequency of HaLow?",
          ["900 Hz", "Sub-1 Ghz", "2.4 Ghz", "5 Ghz"],
          "Sub-1 Ghz",
          "HaLow operates in sub-1 GHz bands."),

        q("t6q16", "multi-select",
          "Select the true statements for WiFi",
          ["Its frequency ranges from 2.4Ghz to 2.5Ghz",
           "The 5Ghz Band has a 150Mhz bandwidth",
           "Its frequency ranges from 5Ghz to 5.15Ghz",
           "The 2.4Ghz Band has a 150Mhz bandwidth"],
          ["Its frequency ranges from 2.4Ghz to 2.5Ghz",
           "The 5Ghz Band has a 150Mhz bandwidth"],
          "WiFi 2.4GHz spans 2.4-2.5GHz; 5GHz band has ~150MHz bandwidth."),

        q("t6q17", "multi-select",
          "Which of the following frames are transmitted by the Access Point when a node is attempting to join a Basic Service Set using active scanning? (You can select more than one)",
          ["Probe Response Frame", "Association Request Frame", "Association Response Frame", "Probe Request Frame"],
          ["Probe Response Frame", "Association Response Frame"],
          "AP sends Probe Response and Association Response during active scanning."),

        q("t6q18", "multi-select",
          "Which of the following frames are transmitted by a node when it is attempting to join a Basic Service Set using passive scanning? (You can select more than one)",
          ["Probe Request Frame", "Association Request Frame", "Probe Response Frame", "Association Response Frame"],
          ["Association Request Frame"],
          "In passive scanning, the node sends Association Request after listening for beacons."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 7 – Bluetooth
# ---------------------------------------------------------------------------
topic7 = {
    "topicId": 7,
    "topicName": "Bluetooth",
    "questions": [
        q("t7q1", "mcq",
          "What does BLE stand for?",
          ["Bluetooth Long Engagement", "Bluetooth Low Efficiency", "Bluetooth Low Energy", "Basic Link Encryption"],
          "Bluetooth Low Energy",
          "BLE stands for Bluetooth Low Energy."),

        q("t7q2", "mcq",
          "Which of the following scheme is used by Bluetooth?",
          ["Pyramid scheme", "Frequency hopping TDD scheme", "VWXYZ scheme",
           "DSSS TDD scheme", "Frequency hopping FDD scheme", "ABCDEFG scheme", "DSSS FDD scheme"],
          "Frequency hopping TDD scheme",
          "Bluetooth uses frequency hopping with TDD."),

        q("t7q3", "mcq",
          "Which version of Bluetooth introduced BLE?",
          ["Bluetooth 5.0", "Bluetooth 4.0", "Bluetooth 2.0", "Bluetooth 3.0"],
          "Bluetooth 4.0",
          "BLE was introduced in Bluetooth 4.0."),

        q("t7q4", "mcq",
          "Which frequency band does BLE operate in?",
          ["915 MHz", "5.0 GHz", "433 MHz", "868 MHz", "2.4 GHz"],
          "2.4 GHz",
          "BLE operates in the 2.4 GHz ISM band."),

        q("t7q5", "mcq",
          "Which of the following supports low energy radio operation.",
          ["Bluetooth", "BLE", "HaLow", "WiFi"],
          "BLE",
          "BLE specifically supports low energy radio operation."),

        q("t7q6", "text-input",
          "Bluetooth is designed for short broadcast. There are forty 2-Mhz channels. How many of these channels are reserved for advertising? (enter numerical number)",
          [],
          "3",
          "3 of the 40 channels are reserved for advertising."),

        q("t7q7", "mcq",
          "In BLE, what is the role of a 'Central' device?",
          ["It acts as an intermediary between two devices.",
           "It broadcasts data to peripheral devices.",
           "It only receives data.",
           "It connects to and controls peripheral devices."],
          "It connects to and controls peripheral devices.",
          "The Central device connects to and controls peripherals."),

        q("t7q8", "mcq",
          "Which feature distinguishes BLE from Classic Bluetooth?",
          ["Longer range.", "Better audio quality.", "Higher data transfer rates.", "Lower energy consumption."],
          "Lower energy consumption.",
          "BLE is distinguished by lower energy consumption."),

        q("t7q9", "mcq",
          "BLE is particularly designed for:",
          ["Long-distance communication.", "Audio streaming.", "Short-range, low-power communication.", "High-speed data transfer."],
          "Short-range, low-power communication.",
          "BLE is designed for short-range, low-power communication."),

        q("t7q10", "mcq",
          "What is the range typically achievable with BLE technology?",
          ["Up to 100 meters", "Up to 150 meters", "Up to 50 meters", "Up to 10 meters"],
          "Up to 100 meters",
          "BLE typically achieves up to 100 meters."),

        q("t7q11", "text-input",
          "Assume Bob can send 300 bits in one slot while using Bluetooth. How many slots does it take to send 600 bits?",
          [],
          "3",
          "With TDD: TX-RX-TX = 3 slots for 2 data transmissions."),

        q("t7q12", "text-input",
          "Assume Bob can send 300 bits in one slot while using Bluetooth. How many slots does it take to send 1200 bits?",
          [],
          "5",
          "With Bluetooth TDD multi-slot, 1200 bits requires 5 slots."),

        q("t7q13", "mcq",
          "What does 'Pairing' in BLE involve?",
          ["Connecting two devices for data transfer.",
           "Exchanging security keys for secure communication.",
           "Adjusting the power level for optimal connection.",
           "Broadcasting data to multiple devices."],
          "Exchanging security keys for secure communication.",
          "BLE pairing involves exchanging security keys."),

        q("t7q14", "mcq",
          "In BLE terminology, what is a 'GATT'?",
          ["Generic Access Transmission Technique",
           "Generic Authentication Transfer Tool",
           "Generic Attribute Profile",
           "Generic Audio Transmission Technology"],
          "Generic Attribute Profile",
          "GATT = Generic Attribute Profile."),

        q("t7q15", "mcq",
          "What is a characteristic of BLE 'Advertising' mode?",
          ["High data transfer rate.",
           "Long-range communication.",
           "Secure data encryption.",
           "Device discovery and connection establishment."],
          "Device discovery and connection establishment.",
          "Advertising mode is used for device discovery and connection establishment."),

        q("t7q16", "multi-select",
          "Which of the following Topology does Bluetooth 4.0 support?",
          ["Ring", "Scatter Net", "Star", "Mesh"],
          ["Scatter Net", "Star"],
          "Bluetooth 4.0 supports Star and Scatter Net topologies."),

        q("t7q17", "mcq",
          "What is the maximum data rate of latest BLE?",
          ["4 Mbps5", "1 Mbps", "2 Mbps", "3 Mbps"],
          "2 Mbps",
          "Latest BLE supports up to 2 Mbps."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 8 – AIoT & Cloud
# ---------------------------------------------------------------------------
topic8 = {
    "topicId": 8,
    "topicName": "AIoT & Cloud",
    "questions": [
        q("t8q1", "mcq",
          "Which of the following is not a benefit of AIoT? (pick the best answer)",
          ["Enhanced security", "Increased productivity", "Improved energy efficiency", "Decreased complexity"],
          "Decreased complexity",
          "AIoT actually increases complexity."),

        q("t8q2", "mcq",
          "AIoT stands for?",
          ["Artificial Internet of Things", "Artificial Intelligence of Things", "Advanced IoT", "Artificial Intelligence on IoT"],
          "Artificial Intelligence on IoT",
          "AIoT = Artificial Intelligence on IoT."),

        q("t8q3", "multi-select",
          "Which if the following is TRUE about Fog Computing?",
          ["Fog computing are located nearer to the Cloud computing",
           "Cloud is a centralized system, while the fog is a distributed decentralized infrastructure",
           "Fog provides low latency",
           "Fog computing is a separate architecture that can replace cloud computing."],
          ["Cloud is a centralized system, while the fog is a distributed decentralized infrastructure",
           "Fog provides low latency"],
          "Fog is decentralized and provides low latency."),

        q("t8q4", "mcq",
          "Which if the following is NOT a Cloud Service Model?",
          ["Infrastructure as a Service", "Virtualization as a Service", "Software as a Service", "Platform as a Service"],
          "Virtualization as a Service",
          "The three cloud service models are IaaS, PaaS, SaaS."),

        q("t8q5", "mcq",
          "Base on the lecture, which of the following is NOT an advantage of Cloud Computing?",
          ["Resilient", "Virtualization", "Management", "Integration"],
          "Integration",
          "Integration is not listed as an advantage of cloud computing."),

        q("t8q6", "mcq",
          "Which of the following is a good example of an AIoT application?",
          ["A fitness tracker that monitors your heart rate and sleep patterns",
           "A smart home thermostat that learns your preferences over time",
           "A wearable device that tracks your steps and calories burned",
           "A wireless security camera that sends alerts to your smartphone"],
          "A smart home thermostat that learns your preferences over time",
          "A learning thermostat combines AI (learning) with IoT (connected device)."),

        q("t8q7", "mcq",
          "What is the name of the cloud service model that provides access to software applications over the internet?",
          ["Function as a Service (FaaS)",
           "Software as a Service (SaaS)",
           "Platform as a Service (PaaS)",
           "Infrastructure as a Service (IaaS)"],
          "Software as a Service (SaaS)",
          "SaaS provides software over the internet."),

        q("t8q8", "mcq",
          "Based on the lecture, which of the following is not a typical deployment challenge for Edge computing devices.",
          ["Thermal", "Power", "Sound proofing", "Waterproofing"],
          "Sound proofing",
          "Sound proofing is not a typical edge computing deployment challenge."),

        q("t8q9", "mcq",
          "Which of the following is not a potential use case for AIoT in industrial automation?",
          ["Quality control", "Employee time tracking", "Inventory management", "Predictive maintenance"],
          "Employee time tracking",
          "Employee time tracking is not a typical AIoT industrial use case."),

        q("t8q10", "mcq",
          "Which of the following is a benefit of cloud computing?",
          ["Limited data accessibility", "Lower maintenance costs", "Limited scalability", "Higher upfront costs"],
          "Lower maintenance costs",
          "Cloud computing reduces maintenance costs."),

        q("t8q11", "mcq",
          "Which of the following is NOT an advantage of Edge Computing?",
          ["Faster response time",
           "Low investment cost",
           "Significantly reduced data storage requirements",
           "Reduces Network Bandwidth Requirements"],
          "Low investment cost",
          "Edge computing requires additional hardware investment."),

        q("t8q12", "mcq",
          "Which if the following statement is FALSE?",
          ["Type 1 Hypervisor are also known as Bare metal hypervisor.",
           "Type 1 Hypervisor do not use host OS.",
           "Type 2 Hypervisor use host OS.",
           "Type 2 Hypervisor are also known as Bare metal hypervisor."],
          "Type 2 Hypervisor are also known as Bare metal hypervisor.",
          "Type 1 (not Type 2) are bare metal hypervisors."),

        q("t8q13", "mcq",
          "What is Cloud Computing?",
          ["It is a way to access software and services over the internet.",
           "It is a way to store data on your local computer.",
           "It is a way to physically connect multiple computers together.",
           "It is a way to protect data from unauthorized access."],
          "It is a way to access software and services over the internet.",
          "Cloud computing provides access to services over the internet."),

        q("t8q14", "mcq",
          "What is IaaS?",
          ["Interaction as a Service", "Infrastructure as a Service", "Internet as a Service", "Intelligence as a Service"],
          "Infrastructure as a Service",
          "IaaS = Infrastructure as a Service."),

        q("t8q15", "mcq",
          "What is the purpose of AIoT?",
          ["To replace IoT devices with AI-powered devices",
           "To improve the design of IoT devices",
           "To create a secure network for IoT devices",
           "To integrate artificial intelligence with the internet of things"],
          "To integrate artificial intelligence with the internet of things",
          "AIoT integrates AI with IoT."),

        q("t8q16", "mcq",
          "Which of the following is a limitation of AIoT?",
          ["It can be expensive to implement",
           "It requires a high degree of technical expertise to implement",
           "It is limited by the processing power of IoT devices",
           "It is only suitable for large-scale applications"],
          "It is limited by the processing power of IoT devices",
          "IoT devices have limited processing power for AI."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 9 – Cellular IoT
# ---------------------------------------------------------------------------
topic9 = {
    "topicId": 9,
    "topicName": "Cellular IoT",
    "questions": [
        q("t9q1", "mcq",
          "Which of the following organizations is responsible for the development of NB-IoT standards?",
          ["3GPP", "IETF", "Wi-Fi Alliance", "IEEE"],
          "3GPP",
          "3GPP develops NB-IoT standards."),

        q("t9q2", "mcq",
          "Assume that you are a network operator, and you chose to implement TDMA as the multiple access scheme. How much bandwidth is required to support 10 users if each user requires a bandwidth equal to 400kHz. Assume that the bandwidth of the guard band on each side of the spectrum must be equal to 50kHz.",
          ["4100kHz", "400kHz", "500kHz", "4000kHz"],
          "500kHz",
          "TDMA: all users share the same bandwidth. BW = 400kHz + 2\u00d750kHz = 500kHz."),

        q("t9q3", "mcq",
          "Which of the following IoT applications is best suited for NB-IoT? Choose the best one.",
          ["Real-time video streaming", "Wearable fitness trackers", "Smart metering in rural areas", "High-speed asset tracking"],
          "Smart metering in rural areas",
          "NB-IoT is ideal for low-data-rate, long-range applications like smart metering."),

        q("t9q4", "mcq",
          "Consider the following two statements and select the appropriate option below:\nStatement A: NB-IoT requires the device to connect to an operator network via licensed or unlicensed spectrum. The spectrum in which the devices are transmitting information does not matter if the eNodeB (i.e., the 4G cellular tower) is aware of the same.\nStatement B: Unlike normal LTE devices, NB-IoT devices need not listen to paging regularly. In fact, it is okay even if these devices do not listen to paging for a whole day as well.",
          ["Both Statements are false.",
           "Statement B is true, but Statement A is false.",
           "Statements A and B are true.",
           "Statement A is true, but Statement B is false."],
          "Both Statements are false.",
          "NB-IoT uses licensed spectrum only, and devices still need periodic paging."),

        q("t9q5", "mcq",
          "Link Budget ...",
          ["refers to the amount of loss that a data link (transmitter to receiver) should have.",
           "refers to the difference between the minimum expected power received at the receiver's end, and the receiver's sensitivity.",
           "refers to a connection between two entities.",
           "refers to the amount of loss that a data link (transmitter to receiver) can tolerate in order to operate properly."],
          "refers to the amount of loss that a data link (transmitter to receiver) can tolerate in order to operate properly.",
          "Link budget is the maximum tolerable loss in a data link."),

        q("t9q6", "mcq",
          "NB-IoT is introduced in which of the following standards?",
          ["LTE - Advanced Pro", "LTE - NB Advanced", "LTE - Advanced", "LTE"],
          "LTE - Advanced Pro",
          "NB-IoT was introduced in LTE-Advanced Pro (3GPP Release 13)."),

        q("t9q7", "mcq",
          "Which of the following is not a feature of NB-IoT?",
          ["Extended Coverage", "Extended Idle Mode", "High Receiver Sensitivity", "Long Battery Life"],
          "High Receiver Sensitivity",
          "NB-IoT features extended coverage, extended idle mode, and long battery life."),

        q("t9q8", "mcq",
          "Why is NIDD particularly suitable for NB-IoT?",
          ["It allows direct device-to-device communication",
           "It uses a broadcast communication model",
           "It supports high-bandwidth applications",
           "It eliminates IP overhead, optimizing for small data packets"],
          "It eliminates IP overhead, optimizing for small data packets",
          "NIDD eliminates IP overhead for small NB-IoT data packets."),

        q("t9q9", "mcq",
          "Assume that you are a network operator, and you are allocated a frequency spectrum of bandwidth equal to 1000kHz for carrying out 4G cellular operation. How many subcarriers (maximum) can you support given the above bandwidth. Assume that the bandwidth of the guard band on each side of the spectrum must be equal to 50kHz.",
          ["70", "60", "40", "50"],
          "60",
          "Usable BW = 1000 - 2\u00d750 = 900kHz. Subcarriers = 900/15 = 60."),

        q("t9q10", "mcq",
          "Assume that you are a network operator, and you are allocated a frequency spectrum of bandwidth equal to 1000kHz for carrying out cellular operation. You chose to implement FDMA as the multiple access scheme. How many users can you support if each user requires a bandwidth equal to 40kHz. Assume that the bandwidth of the guard band on each side of the spectrum must be equal to 50kHz.",
          ["24", "22", "25", "23"],
          "22",
          "Usable BW = 1000 - 2\u00d750 = 900kHz. Users = floor(900/40) = 22."),

        q("t9q11", "mcq",
          "Consider the following two statements and select the appropriate option below:\nStatement A: NB-IoT devices are not suitable for indoor placement due to insufficient coverage, making it challenging to support devices located inside buildings.\nStatement B: NB-IoT devices rely on coverage provided by LTE and 5G-NR cellular technologies.",
          ["Statement A is true, but Statement B is false.",
           "Statements A and B are true. Statement B is the perfect explanation for Statement A.",
           "Statement B is true, but Statement A is false.",
           "Both Statements are false.",
           "Statements A and B are true. Statement B and Statement A are independent of each other."],
          "Statement B is true, but Statement A is false.",
          "NB-IoT has enhanced indoor coverage. It does rely on LTE/5G-NR coverage."),

        q("t9q12", "mcq",
          "Which of the following is NOT a mode of operations for NB-IoT?",
          ["Guard band", "Stand Alone", "In-Band", "Out-Band"],
          "Out-Band",
          "NB-IoT modes are In-Band, Guard Band, and Stand Alone."),

        q("t9q13", "mcq",
          "Which of the following is a key advantage of NB-IoT over traditional cellular networks?",
          ["High Data Rates", "Wide Coverage Area", "High Reliability", "Low Power Consumption"],
          "Low Power Consumption",
          "NB-IoT's key advantage is low power consumption."),

        q("t9q14", "text-input",
          "Assume NB-IoT scenario and calculate the minimum transmit power for a link budget equal to 170dB and receiver sensitivity equal to -150dBm. Enter the numerical number only in dBm.",
          [],
          "20",
          "TX power = Link Budget + Sensitivity = 170 + (-150) = 20 dBm."),

        q("t9q15", "mcq",
          "Assume that the subcarrier band size has been increased from 15kHz to 25kHz. Using this information, calculate how much would be the bandwidth of one physical resource block. Select which of the following is the answer:",
          ["300kHz", "500kHz", "250kHz", "375kHz"],
          "300kHz",
          "Resource block = 12 subcarriers \u00d7 25kHz = 300kHz."),

        q("t9q16", "mcq",
          "Consider the following two statements and select the appropriate option below:\nStatement A: Any mobile connected to a 4G network can move while retaining an active connection.\nStatement B: As NB-IoT devices rely on coverage provided by 4G, they can also move while maintaining an active connection.",
          ["Statement A is true, but Statement B is false.",
           "Statements A and B are true. Statement B is the perfect explanation for Statement A.",
           "Statements A and B are true. Statement B and Statement A are independent of each other.",
           "Both Statements are false.",
           "Statement B is true, but Statement A is false."],
          "Statement A is true, but Statement B is false.",
          "4G supports handover/mobility, but NB-IoT does not support handover."),

        q("t9q17", "mcq",
          "A network manager chose to use QPSK (Quadrature Phase Shift Keying) as the modulation scheme for the NB-IoT network. Given this scenario, select how many bits can an NB-IoT transmit at any given point of time. (Select only the possible option)",
          ["None of the above", "Two bits", "All of the above", "Three bits", "Only one bit"],
          "None of the above",
          "NB-IoT uses single-tone with pi/2-BPSK or pi/4-QPSK, not standard QPSK."),

        q("t9q18", "mcq",
          "Which network element is responsible for interfacing NIDD with IoT application servers in NB-IoT?",
          ["MME", "EPC", "S-GW", "SCEF"],
          "SCEF",
          "SCEF interfaces NIDD with IoT application servers."),

        q("t9q19", "mcq",
          'Which of the following features of NB-IoT reduces power consumption by allowing devices to "sleep" for extended periods?',
          ["VoLTE", "PSM", "eDRX", "NIDD"],
          "PSM",
          "PSM (Power Saving Mode) allows extended sleep periods."),

        q("t9q20", "mcq",
          "Which of the following codes, used in CDMA, are considered orthogonal codes?",
          ["All of the above",
           "<0,0,1,1> and <1,0,1,0>",
           "<0,1,0,1> and <1,0,1,0>",
           "<0,1,0,1> and <1,0,0,1>"],
          "<0,1,0,1> and <1,0,1,0>",
          "Orthogonal codes have zero cross-correlation."),

        q("t9q21", "multi-select",
          "If the hopping time, assuming FHSS, is equal to 500\u00b5s, how many times would the signal hopped in one second? (you can select more than one option)",
          ["1500", "2250", "2000", "1750", "2500"],
          ["1500", "2000", "1750"],
          "1/500us = 2000 hops/sec. Values <= 2000 are valid: 1500, 1750, 2000."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 10 – 802.15.4 & Thread
# ---------------------------------------------------------------------------
topic10 = {
    "topicId": 10,
    "topicName": "802.15.4 & Thread",
    "questions": [
        q("t10q1", "mcq",
          "Which of the following is true about Thread Network?",
          ["IPV6 ULA address is used for mesh establishment and link maintenance.",
           "Every Thread device is assigned only one Mesh local address.",
           "Thread enables full mesh connectivity between all the devices in the network.",
           "A thread network can employ more 10 routers in the network.",
           "None of the Above"],
          "A thread network can employ more 10 routers in the network.",
          "Thread networks can employ more than 10 routers."),

        q("t10q2", "text-input",
          'Assume that a user wants to transmit bit 1 using Direct Sequence Spread Spectrum. The user using "XOR" to generate the same. What is the transmitted signal (in binary) if the chipping sequence is 101011010011?',
          [],
          "010100101100",
          "XOR bit 1 with each bit of chipping sequence inverts all bits."),

        q("t10q3", "mcq",
          "Which of the following is not a characteristic of Thread?",
          ["The range of the network is more than enough to cover a home.",
           "Devices can easily join the network.",
           "There is no single point of failure.",
           "All the options are characteristics of Thread.",
           "Thread can support large networks."],
          "Devices can easily join the network.",
          "Thread uses secure commissioning, not easy joining."),

        q("t10q4", "mcq",
          "What does IEEE 802.15.4 primarily focus on?",
          ["Long-range wireless communication",
           "High-bandwidth local area networking",
           "Low-rate wireless personal area networks",
           "High-speed internet connectivity"],
          "Low-rate wireless personal area networks",
          "IEEE 802.15.4 focuses on LR-WPANs."),

        q("t10q5", "mcq",
          "6LowPAN is the same as IEEE802.15.4",
          ["True", "False"],
          "False",
          "6LowPAN is an adaptation layer on top of IEEE 802.15.4."),

        q("t10q6", "mcq",
          "Which of the following is not a characteristic of Thread?",
          ["All the options are characteristics of Thread.",
           "Devices can easily join the network.",
           "Thread can support large networks.",
           "There is no single point of failure.",
           "The range of the network is more than enough to cover a home."],
          "All the options are characteristics of Thread.",
          "Not all are characteristics - devices cannot easily join (secure commissioning required)."),

        q("t10q7", "multi-select",
          "Which of the following are used by IEEE 802.15.4?",
          ["Frequency Hopping Spread Spectrum",
           "Direct Sequence Spread Spectrum",
           "CSMA with Collision Avoidance",
           "CSMA with Collision Detection"],
          ["Direct Sequence Spread Spectrum", "CSMA with Collision Avoidance"],
          "IEEE 802.15.4 uses DSSS and CSMA/CA."),

        q("t10q8", "mcq",
          "6LowPAN uses traditional IPv6 as its networking layer.",
          ["True", "False"],
          "False",
          "6LowPAN uses compressed IPv6, not traditional IPv6."),

        q("t10q9", "text-input",
          "If the number of carrier frequencies is equal to 25, how many outputs bits must be generated by the PRN generator? (Assume FHSS)",
          [],
          "5",
          "2^5 = 32 >= 25, so 5 bits needed."),

        q("t10q10", "text-input",
          "If the bandwidth of the spread spectrum signal is 180MHz and the signal bandwidth is 15MHz. How many carrier frequencies are required for generating the spread spectrum signal?",
          [],
          "12",
          "180/15 = 12 carrier frequencies."),

        q("t10q11", "text-input",
          "Assume Bob is using DSSS to transmit his data to Alice. Bob decided to use the chipping sequence 10110100110 to transmit his bits. Bob transmitted 330 bits to Alice. Using this information, calculate how many actual bits represent Bob's data?",
          [],
          "30",
          "Chipping sequence has 11 chips. 330/11 = 30 data bits."),

        q("t10q12", "mcq",
          "The size of MTU for an 802.15.4 network is equal to 127 bytes. Of which, 802.15.4 header occupies 25 bytes, security option occupies 21 bytes, IPv6 and UDP compressed headers occupy 10 bytes. Given this situation, choose which of the following application layer payloads (only the size of the payload is shown) can be transmitted over the network. Assume Thread protocol is used for the higher layers.",
          ["71", "80", "120", "127", "All of the above"],
          "All of the above",
          "Available payload = 127-25-21-10 = 71 bytes. With fragmentation, all sizes can be transmitted."),

        q("t10q13", "mcq",
          "If the 16-bit address assigned to a device in a 6LowPAN network is 4EA1, what is the IPv6 link local address?",
          ["FE80:4EA1::0", "PAN ID is unknown.", "FE80::4EA1", "FE80::1111:4EA1"],
          "FE80::4EA1",
          "For 16-bit address without PAN ID, link local = FE80::4EA1."),

        q("t10q14", "mcq",
          "The full form of 6LoWPAN is ...",
          ["6 Low Power Wireless Personal Area Network",
           "IPv6 over Low-Power Wide Area Networks",
           "IPv6 over Low-Power Wireless Personal Area Networks",
           "6 Low Power Wide Personal Area Network"],
          "IPv6 over Low-Power Wireless Personal Area Networks",
          "6LoWPAN = IPv6 over Low-Power Wireless Personal Area Networks."),

        q("t10q15", "mcq",
          "Which of the following are not true about 6LowPAN?",
          ["None of the statements are false.",
           "6LowPAN is a networking layer protocol for Internet of Things",
           "6LowPAN has the capability of optional mesh routing in the data link layer",
           "6LowPAN is based on IPv4 and IPv6 protocols for transmitting packets"],
          "6LowPAN is based on IPv4 and IPv6 protocols for transmitting packets",
          "6LowPAN is IPv6-only, not IPv4."),

        q("t10q16", "mcq",
          "If the 16-bit address assigned to a device in a 6LowPAN network is 4EA1, what is the IPv6 link local address? Assume the PAN ID is 5678.",
          ["FE80:5678::4EA1", "FE80::4EA1", "FE80::5678:4EA1", "FE80:5678:4EA1::0"],
          "FE80::5678:4EA1",
          "With PAN ID: FE80::PAN_ID:SHORT_ADDR = FE80::5678:4EA1."),

        q("t10q17", "multi-select",
          "Select the standards that are typically common across IEEE 802.",
          ["802.1 Bridging", "802.3 Ethernet", "802.16 WiMAX", "802.17 Resilient Packet Ring", "802.2 Logical Link Control"],
          ["802.1 Bridging", "802.2 Logical Link Control"],
          "802.1 Bridging and 802.2 LLC are common across IEEE 802 standards."),

        q("t10q18", "mcq",
          "Which type of modulation is used in IEEE 802.15.4?",
          ["Direct Sequence Spread Spectrum (DSSS)",
           "Phase-Shift Keying (PSK)",
           "Orthogonal Frequency-Division Multiplexing (OFDM)",
           "Frequency Shift Keying (FSK)"],
          "Direct Sequence Spread Spectrum (DSSS)",
          "IEEE 802.15.4 uses DSSS."),

        q("t10q19", "text-input",
          'Assume that a user wants to transmit bit 0 using Direct Sequence Spread Spectrum. The user using "XOR" to generate the same. What is the transmitted signal (in binary) if the chipping sequence is 011011000101?',
          [],
          "011011000101",
          "XOR with 0 leaves the chipping sequence unchanged."),

        q("t10q20", "multi-select",
          "IEEE 802.15.4 is a basis for which popular IoT communication protocol?",
          ["LTE", "Bluetooth", "WiFi", "Thread", "ZigBee"],
          ["Thread", "ZigBee"],
          "Both Thread and ZigBee build on IEEE 802.15.4."),

        q("t10q21", "multi-select",
          "IEEE 802.15.4 defines the operation of which network layers?",
          ["Session Layer", "Transport Layer", "Application Layer", "Physical (PHY)", "Data Link Layer", "Network Layer"],
          ["Physical (PHY)", "Data Link Layer"],
          "IEEE 802.15.4 defines PHY and Data Link (MAC) layers."),

        q("t10q22", "mcq",
          "Which of the following is NOT true about Border Routers in a Thread Network?",
          ["Border Router provide services to devices within the Thread Network only.",
           "A REED can be configured as a Border Router in the Thread Network.",
           "Border Router can provide connectivity from Thread Network to 802.11 networks.",
           "There cannot be more than 3 border routers in a Thread Network."],
          "There cannot be more than 3 border routers in a Thread Network.",
          "Thread supports multiple border routers with no limit of 3."),

        q("t10q23", "multi-select",
          "Which of the following phases are required for a device to re-attach to a Thread Network? (You can select more than one)",
          ["Discovery", "Commissioning", "Attaching", "Configuring"],
          ["Discovery", "Attaching"],
          "Re-attaching requires Discovery and Attaching phases."),

        q("t10q24", "multi-select",
          "Which of the following Full Thread Devices have routing capabilities? (You can select more than one)",
          ["Router", "Leader", "Intermediate Routing Device", "Full End Device", "Router Eligible End Device", "PAN coordinator"],
          ["Router", "Leader", "Router Eligible End Device"],
          "Routers, Leaders, and REEDs have routing capabilities."),

        q("t10q25", "mcq",
          "6LowPAN technology sits on top of ...",
          ["IEEE 802.15.16", "Anything within IEEE 802", "IEEE 802.15.11", "IEEE 802.15.4"],
          "IEEE 802.15.4",
          "6LoWPAN sits on top of IEEE 802.15.4."),

        q("t10q26", "mcq",
          "If the EUI64 address of a device is 62::1, what would be its link local IPv6 address. Assume 6LowPAN protocol.",
          ["FE80:0:0:0:60::1", "FE80:0:0:0:62::1", "None of answer mentioned", "FE80:0:0:0:66::1", "FE80:0:0:0:22::1"],
          "FE80:0:0:0:60::1",
          "Flip the 7th bit of EUI-64: 62 hex \u2192 60 hex."),

        q("t10q27", "mcq",
          "Which of the following frames are required to be transmitted using CSMA/CA?",
          ["All the mentioned frames", "Beacons", "Data Frames", "Acknowledgements"],
          "Data Frames",
          "Only Data Frames must use CSMA/CA."),

        q("t10q28", "text-input",
          "Assume Bob is using DSSS to transmit his data to Alice. Bob decided to use the chipping sequence 101101 to transmit his bits. If the length of the packet is 100 bits, how many bit will Bob actually transmit?",
          [],
          "600",
          "100 data bits \u00d7 6 chips per bit = 600 transmitted bits."),

        q("t10q29", "mcq",
          "If the 16-bit address assigned to a device in a 6LowPAN network is 4EA1, what is the IPv6 link local address?",
          ["FE80::1111:4EA1", "PAN ID is unknown.", "FE80::4EA1", "FE80:4EA1::0"],
          "PAN ID is unknown.",
          "Without PAN ID, the link local address cannot be determined using 16-bit address."),

        q("t10q30", "multi-select",
          "What kind of network topology is supported by IEEE 802.15.4?",
          ["Star", "Bus", "Mesh", "Point-to-Point"],
          ["Star", "Mesh", "Point-to-Point"],
          "IEEE 802.15.4 supports Star, Mesh, and Point-to-Point topologies."),

        q("t10q31", "mcq",
          "Which of the following is true about Thread Network?",
          ["IPV6 ULA address is used for mesh establishment and link maintenance.",
           "Every Thread device is assigned only one Mesh local address.",
           "Thread enables full mesh connectivity between all the devices in the network.",
           "A thread network can employ more 10 routers in the network.",
           "None of the Above"],
          "None of the Above",
          "None of the given statements are true about Thread."),
    ],
}

# ---------------------------------------------------------------------------
# TOPIC 11 – ZigBee and Z-Wave
# ---------------------------------------------------------------------------
topic11 = {
    "topicId": 11,
    "topicName": "ZigBee and Z-Wave",
    "questions": [
        q("t11q1", "mcq",
          "What is the role of Zigbee end devices in the Zigbee network?",
          ["Communicates with other nodes", "Controls the network", "Both", "None"],
          "Communicates with other nodes",
          "End devices communicate with their parent nodes."),

        q("t11q2", "mcq",
          "Which network topology is not supported by ZigBee?",
          ["Bus", "Star", "Mesh", "Cluster Tree"],
          "Bus",
          "ZigBee supports Star, Mesh, and Cluster Tree, not Bus."),

        q("t11q3", "mcq",
          "Z-Wave is an implementation of a ZigBee protocol.",
          ["True", "False"],
          "False",
          "Z-Wave and ZigBee are separate protocols."),

        q("t11q4", "multi-select",
          'Which of the following is needed to be a "ZigBee Compliant Product"',
          ["IEEE 802.15.4", "IEEE 802.11", "Application Profile", "ZigBee Stack"],
          ["IEEE 802.15.4", "Application Profile", "ZigBee Stack"],
          "ZigBee compliance requires 802.15.4, Application Profile, and ZigBee Stack."),

        q("t11q5", "mcq",
          "What is the role of Zigbee coordinator in the Zigbee network?",
          ["Controls the network", "Communicates with other nodes", "Both", "None"],
          "Both",
          "The coordinator controls the network and communicates with nodes."),

        q("t11q6", "mcq",
          "Which of the following is not a feature of Zigbee? (choose the best one)",
          ["Real-time Communication", "Large Bandwidth", "High Security", "Low Power Consumption"],
          "Large Bandwidth",
          "ZigBee has low data rates, not large bandwidth."),

        q("t11q7", "mcq",
          "Zigbee have a transport layer.",
          ["True", "False"],
          "False",
          "ZigBee does not have a transport layer."),

        q("t11q8", "mcq",
          "What is the role of Zigbee routers in the Zigbee network?",
          ["Acts as a relay between other nodes", "Controls the network", "Both", "None"],
          "Acts as a relay between other nodes",
          "ZigBee routers relay data between nodes."),

        q("t11q9", "mcq",
          "Which frequency does Z-Wave operate on?",
          ["915 Mhz", "2.4 Ghz", "5 Ghz", "868 Mhz"],
          "868 Mhz",
          "Z-Wave operates on sub-GHz frequencies like 868 MHz."),

        q("t11q10", "mcq",
          "What is the purpose of Zigbee communication?",
          ["Healthcare", "Industrial Control", "Home Automation", "All of the above"],
          "All of the above",
          "ZigBee is used in healthcare, industrial control, and home automation."),

        q("t11q11", "mcq",
          "Which if the following do not contribute in routing in a ZigBee network?",
          ["ZigBee End Device", "ZigBee Coordinator", "ZigBee Router", "ZigBee Master"],
          "ZigBee End Device",
          "End devices cannot route in ZigBee."),
    ],
}

# ---------------------------------------------------------------------------
# Assemble all topics
# ---------------------------------------------------------------------------
topics = [
    topic1,
    topic2,
    topic3,
    topic4,
    topic5,
    topic6,
    topic7,
    topic8,
    topic9,
    topic10,
    topic11,
]

# ---------------------------------------------------------------------------
# Write JSON and print summary
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "questions.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(topics, f, ensure_ascii=False, indent=2)

    print(f"Wrote {out_path}\n")
    total = 0
    for t in topics:
        count = len(t["questions"])
        total += count
        print(f"  Topic {t['topicId']}: {t['topicName']} — {count} questions")
    print(f"\n  Total: {total} questions across {len(topics)} topics")
